# Generated by Django 4.2.6 on 2023-11-13 13:19

import apps.accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_ages_alter_event_name'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='events.ticket'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default=apps.accounts.models.UserProfile.get_empty_user_profile, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='purchase', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bonus',
            field=models.FloatField(default=0),
        ),
    ]
