# Generated by Django 4.2.5 on 2023-10-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="")),
                ("date", models.DateTimeField(verbose_name="")),
                ("description", models.TextField(verbose_name="")),
                (
                    "ages",
                    models.CharField(
                        choices=[
                            ("0+", "0+"),
                            ("6+", "6+"),
                            ("12+", "12+"),
                            ("16+", "16+"),
                            ("18+", "18+"),
                        ],
                        default="0+",
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
