# Generated by Django 4.2.5 on 2023-10-22 09:33

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="genre",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.CharField(
                blank=True, max_length=255, unique=True, verbose_name="url мероприятия"
            ),
        ),
    ]
