# Generated by Django 4.2.5 on 2023-10-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_genre_event_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                default=1, upload_to=".static/img", verbose_name=""
            ),
            preserve_default=False,
        ),
    ]
