# Generated by Django 4.2.5 on 2023-10-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                upload_to="apps/events/static/img", verbose_name=""
            ),
        ),
    ]
