# Generated by Django 4.2.5 on 2023-10-21 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_userprofile_persona_delete_userpersona"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userprofile",
            table="Users",
        ),
    ]
